#!/usr/bin/env python3
"""supa - multi-profile Supabase CLI wrapper.

Each profile is a named Supabase account (an ``sbp_`` access token).
Profiles are stored in a local JSON store (chmod 600, default
``~/.config/supa/profiles.json``).

Commands:
  supa login <profile> [--token T | --from-file]   add/update a profile token.
                                                   Without flags: env SUPABASE_ACCESS_TOKEN, else an
                                                   interactive paste prompt (opens the dashboard page);
                                                   the first profile becomes active automatically
  supa ls [--json]                                 list profiles with their orgs
  supa use <profile>                               make a profile the default (writes ~/.supabase/access-token)
  supa use --none                                  clear the default
  supa current                                     show the active default profile
  supa run <profile> <cmd...>                      run `supabase <cmd...>` with that profile's token
  supa token <profile>                             print a profile's token (for CI/export)
  supa pass-export <profile> [path]                write a profile token into the pass store + git push
  supa rm <profile>                                delete a profile
  supa <cmd...>                                    shorthand: run `supabase <cmd...>` with the active profile

The real Supabase CLI resolves tokens in this order: SUPABASE_ACCESS_TOKEN env -> keychain -> file.
This wrapper injects SUPABASE_ACCESS_TOKEN, so profiles work in headless and agent environments
where the OS keychain is unavailable.

Overridable via environment:
  SUPA_CONFIG_DIR          token store directory (default ~/.config/supa)
  SUPA_ZSH_FILE            zsh token file regenerated on change (default ~/.cache/zsh/supabase-tokens.sh)
  SUPA_ACCESS_TOKEN_FILE   file written by `supa use` (default ~/.supabase/access-token)
  SUPA_API_BASE            Management API base (default https://api.supabase.com/v1)
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.request
from datetime import datetime, timezone

try:
    from . import __version__
except ImportError:  # running as a standalone script, not as a package
    __version__ = "1.1.0"

STORE_DIR = os.environ.get("SUPA_CONFIG_DIR") or os.path.expanduser("~/.config/supa")
STORE_PATH = os.path.join(STORE_DIR, "profiles.json")
ZSH_FILE = os.environ.get("SUPA_ZSH_FILE") or os.path.expanduser("~/.cache/zsh/supabase-tokens.sh")
ACCESS_TOKEN_FILE = os.environ.get("SUPA_ACCESS_TOKEN_FILE") or os.path.expanduser("~/.supabase/access-token")
API_BASE = os.environ.get("SUPA_API_BASE") or "https://api.supabase.com/v1"
TOKEN_RE = re.compile(r"^sbp_(oauth_)?[a-f0-9]{40}$")
NAME_RE = re.compile(r"^[a-zA-Z0-9_-]{1,64}$")


class SupaError(Exception):
    pass


# ---------- store ----------

def load_store() -> dict:
    if os.path.exists(STORE_PATH):
        try:
            with open(STORE_PATH) as fh:
                data = json.load(fh)
            if isinstance(data.get("profiles"), dict):
                return data
        except (json.JSONDecodeError, OSError) as err:
            raise SupaError(f"cannot read {STORE_PATH}: {err}")
    return {"active": None, "profiles": {}}


def save_store(store: dict) -> None:
    os.makedirs(STORE_DIR, mode=0o700, exist_ok=True)
    tmp = STORE_PATH + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(store, fh, indent=2)
    os.chmod(tmp, 0o600)
    os.replace(tmp, STORE_PATH)


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


# ---------- org lookup ----------

def fetch_orgs(token: str) -> list[dict]:
    req = urllib.request.Request(
        f"{API_BASE}/organizations",
        headers={
            "Authorization": f"Bearer {token}",
            "User-Agent": f"supa/{__version__}",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
        return [{"name": o.get("name"), "id": o.get("id")} for o in data if isinstance(o, dict)]
    except urllib.error.HTTPError as err:
        if err.code in (401, 403):
            raise SupaError(f"token rejected by API ({err.code}) - wrong account or revoked")
        raise SupaError(f"org lookup failed: HTTP {err.code}")
    except (urllib.error.URLError, TimeoutError) as err:
        raise SupaError(f"org lookup failed (offline?): {err}")


# ---------- zsh sync ----------

def write_zsh_file(store: dict) -> None:
    os.makedirs(os.path.dirname(ZSH_FILE), mode=0o700, exist_ok=True)
    lines = [
        "# Generated by supa - do not edit by hand.",
        "# One token per Supabase account. Consumed by shell aliases.",
        "",
    ]
    for name, prof in sorted(store["profiles"].items()):
        lines.append(f'__sb_{name}="{prof["token"]}"')
    tmp = ZSH_FILE + ".tmp"
    with open(tmp, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    os.chmod(tmp, 0o600)
    os.replace(tmp, ZSH_FILE)


def import_from_zsh_file(store: dict) -> int:
    """One-time import of tokens from a pre-existing zsh token file."""
    if not os.path.exists(ZSH_FILE) or store["profiles"]:
        return 0
    imported = 0
    try:
        with open(ZSH_FILE) as fh:
            content = fh.read()
    except OSError:
        return 0
    for m in re.finditer(r"__sb_([A-Za-z0-9_]+)=\"([^\"]*)\"", content):
        name, token = m.group(1), m.group(2)
        if token and NAME_RE.match(name) and TOKEN_RE.match(token):
            store["profiles"][name] = {"token": token, "orgs": [], "created": now_iso(), "updated": now_iso()}
            imported += 1
    return imported


# ---------- active profile ----------

def set_active(store: dict, name=None) -> None:
    store["active"] = name
    if name is None:
        return
    token = store["profiles"].get(name, {}).get("token")
    if not token:
        raise SupaError(f"profile '{name}' has no token")
    with open(ACCESS_TOKEN_FILE, "w") as fh:
        fh.write(token)
    os.chmod(ACCESS_TOKEN_FILE, 0o600)


# ---------- token capture ----------

def read_current_cli_token() -> str:
    """Resolve the token the supabase CLI would currently use: keychain('supabase') then the file."""
    try:
        out = subprocess.run(
            ["security", "find-generic-password", "-s", "Supabase CLI", "-a", "supabase", "-w"],
            capture_output=True, text=True, timeout=5,
        )
        if out.returncode == 0:
            token = out.stdout.strip()
            if TOKEN_RE.match(token):
                return token
    except (OSError, subprocess.TimeoutExpired):
        pass
    try:
        token = open(ACCESS_TOKEN_FILE).read().strip()
        if TOKEN_RE.match(token):
            return token
    except OSError:
        pass
    raise SupaError(
        f"no token found in keychain (Supabase CLI/supabase) or {ACCESS_TOKEN_FILE} - "
        "run `supabase login` in a terminal first"
    )


def open_browser(url: str) -> None:
    if sys.platform == "darwin":
        cmd = ["open", url]
    elif sys.platform.startswith("linux"):
        cmd = ["xdg-open", url]
    else:
        cmd = None
    if cmd:
        try:
            subprocess.Popen(cmd)
        except OSError:
            pass


# ---------- pass integration ----------

def pass_default_path(profile: str) -> str:
    return f"supa/profiles/{profile}"


def run_pass(args, input=None, timeout=30):
    """Run a `pass` subcommand with piped stdin (hermetic against interactive prompts)."""
    pass_bin = shutil.which("pass")
    if not pass_bin:
        raise SupaError("pass CLI not found on PATH (install with `brew install pass`)")
    try:
        return subprocess.run(
            [pass_bin, *args], input=input, capture_output=True, text=True, timeout=timeout
        )
    except subprocess.TimeoutExpired:
        raise SupaError(f"pass {' '.join(args)} timed out")


def pass_read_token(profile: str, path=None) -> str:
    """Read a profile token from the pass store (default path supa/profiles/<profile>)."""
    path = path or pass_default_path(profile)
    result = run_pass(["show", path])
    if result.returncode != 0:
        raise SupaError(
            f"cannot read pass entry '{path}' (exit {result.returncode}) - "
            "is it exported? do you have the GPG key?"
        )
    token = result.stdout.strip()
    if not TOKEN_RE.match(token):
        raise SupaError(f"pass entry '{path}' does not contain a valid sbp_ token")
    return token


def pass_export_token(profile: str, token: str, path=None) -> str:
    """Write a profile token into the pass store and push it to the remote."""
    path = path or pass_default_path(profile)
    result = run_pass(["insert", "-m", "-f", path], input=token + "\n")
    if result.returncode != 0:
        raise SupaError(
            f"pass insert failed for '{path}' (exit {result.returncode}): {result.stderr.strip()}"
        )
    result = run_pass(["git", "push"])
    if result.returncode != 0:
        print(f"note: `pass git push` failed - sync manually (exit {result.returncode})", file=sys.stderr)
    return path


# ---------- commands ----------

def cmd_login(args, store: dict) -> int:
    name = args.profile
    if not NAME_RE.match(name):
        raise SupaError(f"invalid profile name: {name!r} (use letters, digits, -, _)")
    token = args.token
    if not token and args.from_file:
        token = read_current_cli_token()
    if not token and getattr(args, "from_pass", None) is not None:
        token = pass_read_token(name, args.from_pass or None)
    if not token:
        token = os.environ.get("SUPABASE_ACCESS_TOKEN", "").strip()
    if not token and sys.stdin.isatty():
        url = "https://supabase.com/dashboard/account/tokens"
        open_browser(url)
        print(f"Opened {url}")
        print("Generate a token for this account, then paste it here and press Enter:")
        token = sys.stdin.readline().strip()
    if not TOKEN_RE.match(token):
        raise SupaError(
            "no token - pass it with --token <T>, set SUPABASE_ACCESS_TOKEN, "
            "use --from-file (captures a recent `supabase login`), or run in a terminal to paste it"
        )
    print("validating token against the Management API... ", end="", flush=True)
    orgs = fetch_orgs(token)
    print("ok")
    existing = store["profiles"].get(name, {})
    store["profiles"][name] = {
        "token": token,
        "orgs": orgs,
        "created": existing.get("created", now_iso()),
        "updated": now_iso(),
    }
    if store.get("active") is None:
        store["active"] = name
    save_store(store)
    write_zsh_file(store)
    org_names = ", ".join(o["name"] for o in orgs) or "(no orgs)"
    print(f"profile '{name}' stored. Orgs: {org_names}")
    print(f"active profile: {store['active']}")
    return 0


def cmd_ls(args, store: dict) -> int:
    changed = False
    for prof in store["profiles"].values():
        if not prof.get("orgs"):
            try:
                prof["orgs"] = fetch_orgs(prof["token"])
                prof["updated"] = now_iso()
                changed = True
            except SupaError:
                pass  # offline or revoked - show "?"
    if changed:
        save_store(store)
    rows = []
    for name, prof in sorted(store["profiles"].items()):
        orgs = ", ".join(o["name"] for o in prof.get("orgs", [])) if prof.get("orgs") else "?"
        rows.append({
            "profile": name,
            "active": store.get("active") == name,
            "orgs": orgs,
            "updated": prof.get("updated", ""),
        })
    if args.json:
        print(json.dumps(rows, indent=2))
        return 0
    if not rows:
        print("no profiles. Add one: supa login <profile> --token <sbp_...>")
        return 0
    width = max(len(r["profile"]) for r in rows)
    print(f"{'PROFILE'.ljust(width)}  {'ACTIVE':<6}  ORGS")
    for r in rows:
        print(f"{r['profile'].ljust(width)}  {(r['active'] and 'yes' or ''):<6}  {r['orgs']}")
    return 0


def cmd_use(args, store: dict) -> int:
    if args.none:
        set_active(store, None)
        save_store(store)
        print("active profile cleared; the access-token file was left as-is")
        return 0
    if args.profile not in store["profiles"]:
        raise SupaError(f"unknown profile '{args.profile}' (see `supa ls`)")
    set_active(store, args.profile)
    save_store(store)
    print(f"active profile: {args.profile}")
    return 0


def cmd_current(store: dict) -> int:
    active = store.get("active")
    if not active:
        print("no active profile (plain `supabase` uses whatever token is in the access-token file)")
        return 0
    prof = store["profiles"].get(active, {})
    orgs = ", ".join(o["name"] for o in prof.get("orgs", [])) if prof.get("orgs") else "?"
    print(f"active: {active}  ({orgs})")
    return 0


def cmd_run(args, store: dict, passthrough: bool = False) -> int:
    if passthrough:
        name = store.get("active")
        cmd = args.cmd
    else:
        name = args.profile
        cmd = args.cmd
    if not cmd:
        raise SupaError("no command given")
    prof = store["profiles"].get(name) if name else None
    if not prof:
        raise SupaError(
            f"profile '{name}' not found (see `supa ls`)" if name else
            "no active profile - run `supa use <profile>` or `supa run <profile> <cmd...>`"
        )
    supabase = shutil.which("supabase")
    if not supabase:
        raise SupaError("supabase CLI not found on PATH")
    env = dict(os.environ)
    env["SUPABASE_ACCESS_TOKEN"] = prof["token"]
    return os.execvpe(supabase, [supabase, *cmd], env)


def cmd_token(args, store: dict) -> int:
    prof = store["profiles"].get(args.profile)
    if not prof:
        raise SupaError(f"unknown profile '{args.profile}'")
    print(prof["token"])
    return 0


def cmd_rm(args, store: dict) -> int:
    if args.profile not in store["profiles"]:
        raise SupaError(f"unknown profile '{args.profile}'")
    del store["profiles"][args.profile]
    if store.get("active") == args.profile:
        store["active"] = None
    save_store(store)
    write_zsh_file(store)
    print(f"profile '{args.profile}' removed")
    return 0


def cmd_pass_export(args, store: dict) -> int:
    prof = store["profiles"].get(args.profile)
    if not prof:
        raise SupaError(f"unknown profile '{args.profile}'")
    path = pass_export_token(args.profile, prof["token"], args.path)
    print(f"profile '{args.profile}' exported to pass: {path}")
    return 0


# ---------- main ----------

def main() -> int:
    argv = [a for a in sys.argv[1:] if a != "--"]
    first = argv[0] if argv else None
    known = {"login", "ls", "use", "current", "run", "token", "rm", "pass-export"}

    store = load_store()
    imported = import_from_zsh_file(store)
    if imported:
        save_store(store)
        write_zsh_file(store)

    if first and first not in known and not first.startswith("-"):
        # passthrough: `supa <supabase args...>` -> run with the active profile
        args = argparse.Namespace(cmd=argv)
        try:
            return cmd_run(args, store, passthrough=True)
        except SupaError as err:
            print(f"supa: error: {err}", file=sys.stderr)
            return 1

    parser = argparse.ArgumentParser(
        prog="supa", description="multi-profile Supabase CLI wrapper",
        epilog=f"version {__version__}",
    )
    parser.add_argument("--version", action="version", version=f"supa {__version__}")
    sub = parser.add_subparsers(dest="command")

    p_login = sub.add_parser("login", help="add/update a profile token")
    p_login.add_argument("profile")
    p_login.add_argument("--token", help="token (sbp_...); else paste at the prompt")
    p_login.add_argument("--from-file", action="store_true", help="capture the token the supabase CLI currently uses (keychain -> file)")
    p_login.add_argument("--from-pass", nargs="?", const="", metavar="PATH",
                         help="read the token from a pass entry (default supa/profiles/<profile>)")

    p_ls = sub.add_parser("ls", help="list profiles")
    p_ls.add_argument("--json", action="store_true")

    p_use = sub.add_parser("use", help="set the active default profile")
    p_use.add_argument("profile", nargs="?")
    p_use.add_argument("--none", action="store_true", help="clear the active profile")

    sub.add_parser("current", help="show the active profile")

    p_run = sub.add_parser("run", help="run `supabase <cmd...>` with a specific profile")
    p_run.add_argument("profile")
    p_run.add_argument("cmd", nargs=argparse.REMAINDER)

    p_token = sub.add_parser("token", help="print a profile token")
    p_token.add_argument("profile")

    p_rm = sub.add_parser("rm", help="delete a profile")
    p_rm.add_argument("profile")

    p_export = sub.add_parser("pass-export", help="write a profile token into the pass store and push it")
    p_export.add_argument("profile")
    p_export.add_argument("path", nargs="?", help="pass entry path (default supa/profiles/<profile>)")

    args, rest = parser.parse_known_args()
    if rest:
        parser.error(f"unexpected arguments: {' '.join(rest)}")

    try:
        if args.command is None:
            # `supa` with no command: run `supabase --help` under the active profile
            args.cmd = ["--help"]
            return cmd_run(args, store, passthrough=True)
        if args.command == "login":
            return cmd_login(args, store)
        if args.command == "ls":
            return cmd_ls(args, store)
        if args.command == "use":
            if not args.profile and not args.none:
                parser.error("use requires a profile name or --none")
            return cmd_use(args, store)
        if args.command == "current":
            return cmd_current(store)
        if args.command == "run":
            return cmd_run(args, store)
        if args.command == "token":
            return cmd_token(args, store)
        if args.command == "rm":
            return cmd_rm(args, store)
        if args.command == "pass-export":
            return cmd_pass_export(args, store)
        parser.error(f"unknown command: {args.command}")
    except SupaError as err:
        print(f"supa: error: {err}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("supa: interrupted", file=sys.stderr)
        return 130
    return 0


if __name__ == "__main__":
    sys.exit(main())
